/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/CentralAjuda': RouteRecordInfo<'/CentralAjuda', '/CentralAjuda', Record<never, never>, Record<never, never>>,
    '/ManualAdmin': RouteRecordInfo<'/ManualAdmin', '/ManualAdmin', Record<never, never>, Record<never, never>>,
    '/ManualFinanceiro': RouteRecordInfo<'/ManualFinanceiro', '/ManualFinanceiro', Record<never, never>, Record<never, never>>,
    '/ManualFuncionario': RouteRecordInfo<'/ManualFuncionario', '/ManualFuncionario', Record<never, never>, Record<never, never>>,
    '/ManualGerente': RouteRecordInfo<'/ManualGerente', '/ManualGerente', Record<never, never>, Record<never, never>>,
    '/ManualMobile': RouteRecordInfo<'/ManualMobile', '/ManualMobile', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/CentralAjuda.vue': {
      routes: '/CentralAjuda'
      views: never
    }
    'src/pages/ManualAdmin.vue': {
      routes: '/ManualAdmin'
      views: never
    }
    'src/pages/ManualFinanceiro.vue': {
      routes: '/ManualFinanceiro'
      views: never
    }
    'src/pages/ManualFuncionario.vue': {
      routes: '/ManualFuncionario'
      views: never
    }
    'src/pages/ManualGerente.vue': {
      routes: '/ManualGerente'
      views: never
    }
    'src/pages/ManualMobile.vue': {
      routes: '/ManualMobile'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
